--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/RegisterLoginForm
build-by-default: true
branches:
- main
projects:
  RegisterLoginForm:
    path: ""
    libs:
    - src: SOFe/Await-Generator/await-generator
      version: ^3.6.1
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^2.1.1
...
