--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NuhDevX/RegisterLoginForm
build-by-default: true
branches:
- main
projects:
  RegisterLoginForm:
    path: ""
    libs:
    - src: poggit/libasynql/libasynql
      version: ^4.2.3
    - src: SOF3/await-generator/await-generator
      version: "^3.0.0"
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^2.1.1
...
