--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/RegisterLoginForm
build-by-default: true
branches:
- main
projects:
  RegisterLoginForm:
    path: ""
    libs:
    - name: SOFe/AwaitGenerator/await-generator
      version: ^3.6.1
...
