name: RegisterLoginForm
version: 1.0.0
main: NuhDev\RegisterLoginForm\Main
api: [5.0.0]
author: NuhDev
commands:
  resetpassword:
    description: Reset password for a player
    permission: registerloginform.resetpassword
permissions:
  registerloginform.resetpassword:
    description: Allows the user to reset player passwords
    default: op
    
